### ISSUE TITLE
integrate travis, coveralls, readthedocs

### ISSUE THREAD

**Issue by bubenkoff** [pytest-dev/pytest-incremental#1]
to keep pytest-dev/* plugins consistent add:

- [x] travis
- [x] coveralls
- [x] readthedocs
- [x] tox

**Comment by hpk42** [comment]
It'd be great if you could add a ``tox.ini``.  You can check other plugins like https://bitbucket.org/hpk42/pytest-pep8 for inspiration.

**Comment by schettino72** [comment]
correct link: https://bitbucket.org/pytest-dev/pytest-pep8
